Repository indmind/rin, pull requests merged in 2018-04, with the labels that each got.

#33 add codecov
  .coafile
  .gitignore
  .travis.yml
  README.md
  package.json
Labels: process/pending_review, size/XS

#34 Add more test
  package.json
  src/commands/babel.js
  src/commands/calc.js
  src/commands/jawaskrip.js
  src/commands/quote.js
  src/commands/scss.js
  src/commands/translate.js
  src/commands/udict.js
  src/vendor/telegram.js
  tests/command/babel.test.js
  tests/command/calc.test.js
  tests/command/jawaskrip.test.js
  tests/command/quote.test.js
  tests/command/scss.test.js
  tests/command/translate.test.js
  tests/command/typescript.test.js
  tests/command/udict.test.js
Labels: process/pending_review, size/M

#50 update package-lock.json
  package-lock.json
Labels: process/pending_review, size/XXL

#52 Add a Codacy badge to README.md
  README.md
Labels: process/pending_review, size/XS

#51 Refactoring code
  .eslintrc
  src/commands/babel.js
  src/commands/calc.js
  src/commands/eval.js
  src/commands/figlet.js
  src/commands/get.js
  src/commands/googl.js
  src/commands/jawaskrip.js
  src/commands/money.js
  src/commands/scss.js
  src/commands/snap.js
  src/commands/translate.js
  src/commands/typescript.js
  src/commands/urban.js
  src/commands/weather.js
  src/commands/wiki.js
  src/core/class.js
  src/core/helper.js
  src/core/rin.js
  src/vendor/cli.js
  src/vendor/discord.js
  src/vendor/telegram.js
  tests/__data__/dummy.txt
  tests/__data__/urban_id.txt
  tests/__data__/urban_search_depth.txt
  tests/__data__/urban_search_plain.txt
  tests/command/udict.test.js
  tests/command/urban.test.js
  tests/core/helper.test.js
  tests/core/rin.test.js
Labels: code quality, process/pending_review, size/XXL

#53 fix isEmpty function
  src/core/helper.js
  tests/core/helper.test.js
Labels: process/pending_review, size/XS

#56 add rin class test
  tests/core/class.test.js
Labels: size/XS, status/ci-approved
