Repository indmind/rin, pull requests merged in 2018-02, with the labels that each got.

#1 add build status in readme
  README.md
Labels: enhancement, status/ci-approved

#4 Revert "add build status in readme"
  README.md
Labels: size/XS, status/ci-approved

#5 fix center not working
  README.md
Labels: size/XS, status/ci-approved

#6 trying to deploy
  .gitignore
  .travis.yml
  package-lock.json
  procfile
Labels: size/XS, status/ci-approved

#8 fix heroku babel error
  package.json
Labels: size/XS, status/ci-approved

#9 Another fix deploy
  .travis.yml
Labels: process/pending_review, size/XS

#10 please work
  .travis.yml
Labels: process/pending_review, size/XS

#11 Deploy again
  .travis.yml
  README.md
  package.json
Labels: process/pending_review, size/XS

#12 another try
  .travis.yml
  Procfile
Labels: process/pending_review, size/XS

#14 Use one handler
  Procfile
  README.md
  src/main.js
  src/vendor/discord.js
  src/vendor/main.js
Labels: size/S, status/ci-approved

#15 fix procfile
  Procfile
Labels: size/XS, status/ci-approved

#16 add simple http server
  src/vendor/main.js
Labels: process/pending_review, size/XS

#17 Fixbugs
  .eslintrc
  Procfile
  README.md
  package-lock.json
  package.json
  src/core/rin.js
  src/main.js
  src/vendor/discord.js
  src/vendor/http.js
  src/vendor/main.js
  src/vendor/telegram.js
Labels: process/pending_review, size/M

#18 add standarize function
  src/core/rin.js
  src/vendor/discord.js
  src/vendor/telegram.js
Labels: size/XS, status/ci-approved

#19 add limitedEval for security
  .eslintrc
  .travis.yml
  src/command/calc.js
Labels: process/pending_review, size/XS

#20 Revert "add limitedEval for security"
  .eslintrc
  .travis.yml
  src/command/calc.js
Labels: process/pending_review, size/XS

#21 fix some security and use error message for calculation error
  src/command/calc.js
Labels: process/pending_review, size/XS

#23 simple changes
  package-lock.json
  package.json
  src/commands/babel.js
  src/commands/calc.js
  src/commands/jawaskrip.js
  src/commands/scss.js
  src/commands/translate.js
  src/commands/udict.js
  src/commands/wiki.js
  src/main.js
Labels: size/XS, status/ci-approved

#24 add eslint rule to add newline before return statement
  .eslintrc
  src/commands/wiki.js
Labels: process/pending_review, size/XS

#25 add eslint rule for newline after import
  .eslintrc
  package-lock.json
  package.json
Labels: size/S, status/ci-approved

#22 add quote command for random quote
  package-lock.json
  package.json
  src/commands/quote.js
Labels: process/pending_review, size/S

#26 highlight codeblock for discord and change default reply
  src/commands/babel.js
  src/commands/jawaskrip.js
  src/commands/scss.js
  src/commands/typescript.js
  src/core/rin.js
  test/__data__/babel.txt
  test/__data__/jawaskrip.txt
Labels: process/pending_review, size/XS

#27 better readme
  README.md
Labels: size/S, status/ci-approved

#28 Add figlet command
  package-lock.json
  package.json
  src/commands/figlet.js
  src/core/rin.js
  src/vendor/discord.js
  src/vendor/telegram.js
Labels: size/XS, status/ci-approved

#29 add money command to convert currency
  package-lock.json
  package.json
  src/commands/money.js
  src/core/rin.js
  src/vendor/cli.js
  src/vendor/discord.js
  src/vendor/telegram.js
Labels: size/S, status/ci-approved
